spring.application.name=badwallet-api
server.port=8080

# PostgreSQL - Base de données dédiée au badwallet-api
spring.datasource.url=jdbc:postgresql://localhost:5432/orm_badwallet
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=passer

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL du payment-service (Pattern Proxy)
payment.service.url=http://localhost:8081

# Activation de l'asynchrone (pour le seeder)
spring.task.execution.pool.core-size=5

# Hikari Connection Pool Config (limit to prevent too many clients error)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
